// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UmbrellaCorp.Data;

#nullable disable

namespace UmbrellaCorporationApp.Migrations
{
    [DbContext(typeof(UmbrellaDbContext))]
    [Migration("20260511164150_AddDirectMessages")]
    partial class AddDirectMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UmbrellaCorp.Models.Archive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchiveReason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DataSnapshot")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SourceRecordId")
                        .HasColumnType("int");

                    b.Property<string>("SourceTable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Archives");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.ClassifiedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("ClassifiedFiles");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.Development", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LeadScientistId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("VirusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeadScientistId");

                    b.HasIndex("VirusId");

                    b.ToTable("Developments");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.EmergencyMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("EmergencyMessages");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.EmergencyProtocol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EmergencyProtocols");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ClearanceLevel")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("longtext");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.IncidentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ReportedById")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ReportedById");

                    b.ToTable("IncidentLogs");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.LabReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("ConfidentialityLevel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("SampleId")
                        .HasColumnType("int");

                    b.Property<int?>("TestSubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("SampleId");

                    b.HasIndex("TestSubjectId");

                    b.ToTable("LabReports");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.Loss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LossDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LossType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SampleId")
                        .HasColumnType("int");

                    b.Property<int?>("TestSubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SampleId");

                    b.HasIndex("TestSubjectId");

                    b.ToTable("Losses");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.Mutation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TestSubjectId")
                        .HasColumnType("int");

                    b.Property<int?>("VirusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestSubjectId");

                    b.HasIndex("VirusId");

                    b.ToTable("Mutations");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.Sample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int?>("ResponsibleScientistId")
                        .HasColumnType("int");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("VirusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResponsibleScientistId");

                    b.HasIndex("VirusId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("VirusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VirusId");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.TestSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("VirusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VirusId");

                    b.ToTable("TestSubjects");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.Virus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AntidoteExists")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DangerLevel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IncubationHours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Symptoms")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Viruses");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.ClassifiedFile", b =>
                {
                    b.HasOne("UmbrellaCorp.Models.Employee", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.Development", b =>
                {
                    b.HasOne("UmbrellaCorp.Models.Employee", "LeadScientist")
                        .WithMany("Developments")
                        .HasForeignKey("LeadScientistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UmbrellaCorp.Models.Virus", "Virus")
                        .WithMany()
                        .HasForeignKey("VirusId");

                    b.Navigation("LeadScientist");

                    b.Navigation("Virus");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.EmergencyMessage", b =>
                {
                    b.HasOne("UmbrellaCorp.Models.Employee", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UmbrellaCorp.Models.Employee", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.IncidentLog", b =>
                {
                    b.HasOne("UmbrellaCorp.Models.Employee", "ReportedBy")
                        .WithMany("IncidentLogs")
                        .HasForeignKey("ReportedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReportedBy");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.LabReport", b =>
                {
                    b.HasOne("UmbrellaCorp.Models.Employee", "Author")
                        .WithMany("LabReports")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UmbrellaCorp.Models.Sample", "Sample")
                        .WithMany()
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UmbrellaCorp.Models.TestSubject", "TestSubject")
                        .WithMany("LabReports")
                        .HasForeignKey("TestSubjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");

                    b.Navigation("Sample");

                    b.Navigation("TestSubject");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.Loss", b =>
                {
                    b.HasOne("UmbrellaCorp.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UmbrellaCorp.Models.Sample", "Sample")
                        .WithMany()
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UmbrellaCorp.Models.TestSubject", "TestSubject")
                        .WithMany()
                        .HasForeignKey("TestSubjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");

                    b.Navigation("Sample");

                    b.Navigation("TestSubject");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.Mutation", b =>
                {
                    b.HasOne("UmbrellaCorp.Models.TestSubject", "TestSubject")
                        .WithMany()
                        .HasForeignKey("TestSubjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UmbrellaCorp.Models.Virus", "Virus")
                        .WithMany()
                        .HasForeignKey("VirusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TestSubject");

                    b.Navigation("Virus");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.Sample", b =>
                {
                    b.HasOne("UmbrellaCorp.Models.Employee", "ResponsibleScientist")
                        .WithMany("Samples")
                        .HasForeignKey("ResponsibleScientistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UmbrellaCorp.Models.Virus", "Virus")
                        .WithMany("Samples")
                        .HasForeignKey("VirusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResponsibleScientist");

                    b.Navigation("Virus");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.Statistic", b =>
                {
                    b.HasOne("UmbrellaCorp.Models.Virus", "Virus")
                        .WithMany()
                        .HasForeignKey("VirusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Virus");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.TestSubject", b =>
                {
                    b.HasOne("UmbrellaCorp.Models.Virus", "Virus")
                        .WithMany("TestSubjects")
                        .HasForeignKey("VirusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Virus");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.Employee", b =>
                {
                    b.Navigation("Developments");

                    b.Navigation("IncidentLogs");

                    b.Navigation("LabReports");

                    b.Navigation("Samples");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.TestSubject", b =>
                {
                    b.Navigation("LabReports");
                });

            modelBuilder.Entity("UmbrellaCorp.Models.Virus", b =>
                {
                    b.Navigation("Samples");

                    b.Navigation("TestSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
